replicaCount: 3

image:
  repository: 713287746880.dkr.ecr.us-east-1.amazonaws.com/artemis
  tag: "2.0.0"

imagePullSecrets:
  - regcred



service:
  type: ClusterIP
  port: 5000


ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-artemis.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.projectxconsulting.net
