replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: argo-demo-test.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: argo-demo-test-tls
      hosts:
        - argo-demo-test.projectxconsulting.net
